/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package itson.org.laboratorio_algoritmos.gui;

import itson.org.laboratorio_algoritmos.datos.GeneradorDeArreglos;
import itson.org.laboratorio_algoritmos.datos.ResultadoOrdenamiento;
import itson.org.laboratorio_algoritmos.datos.TipoAlgoritmo;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author nafbr
 */
public class FrmSetup extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmSetup.class.getName());

    /**
     * Creates new form SetupForm
     */
    public FrmSetup() {
        initComponents();
        configurarBotonAnalizar();
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgrpOrden = new javax.swing.ButtonGroup();
        pnlPrincipal = new javax.swing.JPanel();
        pnlHeader = new itson.org.laboratorio_algoritmos.gui.utils.PanelRedondeado();
        lblTitulo = new javax.swing.JLabel();
        lblTitulo1 = new javax.swing.JLabel();
        pnlCreacion = new itson.org.laboratorio_algoritmos.gui.utils.PanelRedondeado();
        lblCreacion = new javax.swing.JLabel();
        txtCantidad = new itson.org.laboratorio_algoritmos.gui.utils.TextFieldRedondeado();
        lblCantidad = new javax.swing.JLabel();
        lblOrden = new javax.swing.JLabel();
        rbtnOrdenados = new javax.swing.JRadioButton();
        rbtnCasiOrdenado = new javax.swing.JRadioButton();
        rbtnInvertido = new javax.swing.JRadioButton();
        rbtnDesordenado = new javax.swing.JRadioButton();
        panelRedondeado2 = new itson.org.laboratorio_algoritmos.gui.utils.PanelRedondeado();
        lblAlgoritmos = new javax.swing.JLabel();
        chkBubble = new javax.swing.JCheckBox();
        chkSelection = new javax.swing.JCheckBox();
        chkInsertion = new javax.swing.JCheckBox();
        chkMerge = new javax.swing.JCheckBox();
        chkQuick = new javax.swing.JCheckBox();
        chkHeap = new javax.swing.JCheckBox();
        btnAnalizar = new itson.org.laboratorio_algoritmos.gui.utils.BotonRedondeado();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setBackground(new java.awt.Color(237, 248, 255));

        pnlHeader.setBackground(new java.awt.Color(208, 220, 254));

        lblTitulo.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(31, 0, 78));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Laboratorio de algoritmos de");

        lblTitulo1.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        lblTitulo1.setForeground(new java.awt.Color(31, 0, 78));
        lblTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo1.setText("ordenamiento");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitulo1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlCreacion.setBackground(new java.awt.Color(208, 220, 254));

        lblCreacion.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        lblCreacion.setForeground(new java.awt.Color(31, 0, 78));
        lblCreacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreacion.setText("Creación del arreglo");

        lblCantidad.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        lblCantidad.setForeground(new java.awt.Color(31, 0, 78));
        lblCantidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCantidad.setText("Cantidad de elementos:");

        lblOrden.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        lblOrden.setForeground(new java.awt.Color(31, 0, 78));
        lblOrden.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrden.setText("Elegir orden de los datos:");

        rbtnOrdenados.setBackground(new java.awt.Color(208, 220, 254));
        bgrpOrden.add(rbtnOrdenados);
        rbtnOrdenados.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        rbtnOrdenados.setForeground(new java.awt.Color(31, 0, 78));
        rbtnOrdenados.setSelected(true);
        rbtnOrdenados.setText("Ordenados");
        rbtnOrdenados.setActionCommand("Ordenados");

        rbtnCasiOrdenado.setBackground(new java.awt.Color(208, 220, 254));
        bgrpOrden.add(rbtnCasiOrdenado);
        rbtnCasiOrdenado.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        rbtnCasiOrdenado.setForeground(new java.awt.Color(31, 0, 78));
        rbtnCasiOrdenado.setText("Casi ordenados");

        rbtnInvertido.setBackground(new java.awt.Color(208, 220, 254));
        bgrpOrden.add(rbtnInvertido);
        rbtnInvertido.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        rbtnInvertido.setForeground(new java.awt.Color(31, 0, 78));
        rbtnInvertido.setText("Ordenados de manera inversa");

        rbtnDesordenado.setBackground(new java.awt.Color(208, 220, 254));
        bgrpOrden.add(rbtnDesordenado);
        rbtnDesordenado.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        rbtnDesordenado.setForeground(new java.awt.Color(31, 0, 78));
        rbtnDesordenado.setText("Totalmente desordenados");

        javax.swing.GroupLayout pnlCreacionLayout = new javax.swing.GroupLayout(pnlCreacion);
        pnlCreacion.setLayout(pnlCreacionLayout);
        pnlCreacionLayout.setHorizontalGroup(
            pnlCreacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCreacionLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlCreacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblOrden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlCreacionLayout.createSequentialGroup()
                        .addComponent(lblCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCreacionLayout.createSequentialGroup()
                        .addGroup(pnlCreacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnCasiOrdenado, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtnOrdenados, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtnInvertido, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtnDesordenado, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCreacionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        pnlCreacionLayout.setVerticalGroup(
            pnlCreacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCreacionLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblCreacion)
                .addGap(18, 18, 18)
                .addGroup(pnlCreacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCantidad))
                .addGap(18, 18, 18)
                .addComponent(lblOrden)
                .addGap(18, 18, 18)
                .addComponent(rbtnOrdenados)
                .addGap(18, 18, 18)
                .addComponent(rbtnCasiOrdenado)
                .addGap(18, 18, 18)
                .addComponent(rbtnInvertido)
                .addGap(18, 18, 18)
                .addComponent(rbtnDesordenado)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        panelRedondeado2.setBackground(new java.awt.Color(208, 220, 254));

        lblAlgoritmos.setFont(new java.awt.Font("Corbel", 1, 20)); // NOI18N
        lblAlgoritmos.setForeground(new java.awt.Color(31, 0, 78));
        lblAlgoritmos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAlgoritmos.setText("Algoritmos a comparar");

        chkBubble.setBackground(new java.awt.Color(208, 220, 254));
        chkBubble.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        chkBubble.setText("Bubble sort");

        chkSelection.setBackground(new java.awt.Color(208, 220, 254));
        chkSelection.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        chkSelection.setText("Selection sort");

        chkInsertion.setBackground(new java.awt.Color(208, 220, 254));
        chkInsertion.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        chkInsertion.setText("Insertion sort");

        chkMerge.setBackground(new java.awt.Color(208, 220, 254));
        chkMerge.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        chkMerge.setText("Merge sort");

        chkQuick.setBackground(new java.awt.Color(208, 220, 254));
        chkQuick.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        chkQuick.setText("Quick sort");

        chkHeap.setBackground(new java.awt.Color(208, 220, 254));
        chkHeap.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        chkHeap.setText("Heap sort");

        javax.swing.GroupLayout panelRedondeado2Layout = new javax.swing.GroupLayout(panelRedondeado2);
        panelRedondeado2.setLayout(panelRedondeado2Layout);
        panelRedondeado2Layout.setHorizontalGroup(
            panelRedondeado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeado2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelRedondeado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAlgoritmos, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelRedondeado2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(panelRedondeado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkSelection)
                            .addComponent(chkBubble)
                            .addComponent(chkInsertion)
                            .addComponent(chkMerge)
                            .addComponent(chkQuick)
                            .addComponent(chkHeap))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panelRedondeado2Layout.setVerticalGroup(
            panelRedondeado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeado2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblAlgoritmos)
                .addGap(18, 18, 18)
                .addComponent(chkBubble)
                .addGap(18, 18, 18)
                .addComponent(chkSelection)
                .addGap(18, 18, 18)
                .addComponent(chkInsertion)
                .addGap(18, 18, 18)
                .addComponent(chkMerge)
                .addGap(18, 18, 18)
                .addComponent(chkQuick)
                .addGap(18, 18, 18)
                .addComponent(chkHeap)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAnalizar.setBackground(new java.awt.Color(208, 220, 254));
        btnAnalizar.setForeground(new java.awt.Color(31, 0, 78));
        btnAnalizar.setText("Analizar");
        btnAnalizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        btnAnimacion = new itson.org.laboratorio_algoritmos.gui.utils.BotonRedondeado();
        btnAnimacion.setBackground(new java.awt.Color(208, 220, 254));
        btnAnimacion.setForeground(new java.awt.Color(31, 0, 78));
        btnAnimacion.setText("Animaci\u00f3n");
        btnAnimacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
         btnAnimacion.addActionListener(e -> {
            String texto = txtCantidad.getText().trim();
            if (texto.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(
                    FrmSetup.this,
                    "Debes ingresar una cantidad de elementos.",
                    "Campo vac\u00edo",
                    javax.swing.JOptionPane.WARNING_MESSAGE
                );
                return;
            }
            int tamano;
            try {
                tamano = Integer.parseInt(texto);
            } catch (NumberFormatException ex) {
                javax.swing.JOptionPane.showMessageDialog(
                    FrmSetup.this,
                    "La cantidad debe ser un n\u00famero entero v\u00e1lido.",
                    "N\u00famero inv\u00e1lido",
                    javax.swing.JOptionPane.WARNING_MESSAGE
                );
                return;
            }
            if (tamano < 10 || tamano > 200) {
                javax.swing.JOptionPane.showMessageDialog(
                    FrmSetup.this,
                    "La animaci\u00f3n requiere entre 10 y 200 elementos.",
                    "Fuera de rango",
                    javax.swing.JOptionPane.WARNING_MESSAGE
                );
                return;
            }
            itson.org.laboratorio_algoritmos.datos.GeneradorDeArreglos.TipoArreglo tipo;
            if (rbtnOrdenados.isSelected()) {
                tipo = itson.org.laboratorio_algoritmos.datos.GeneradorDeArreglos.TipoArreglo.ORDENADO;
            } else if (rbtnCasiOrdenado.isSelected()) {
                tipo = itson.org.laboratorio_algoritmos.datos.GeneradorDeArreglos.TipoArreglo.CASI_ORDENADO;
            } else if (rbtnInvertido.isSelected()) {
                tipo = itson.org.laboratorio_algoritmos.datos.GeneradorDeArreglos.TipoArreglo.INVERSO;
            } else {
                tipo = itson.org.laboratorio_algoritmos.datos.GeneradorDeArreglos.TipoArreglo.ALEATORIO;
            }
            FrmAnimacion animacion = new FrmAnimacion(tamano, tipo);
            animacion.setVisible(true);
        });

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(226, 226, 226))
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(pnlCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(panelRedondeado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(btnAnalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAnimacion, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlCreacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRedondeado2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnAnalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnimacion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * Validación para el botón de analizar 
    * Cada validación corta la ejecución con return si falla
    */
    private void configurarBotonAnalizar() {
        btnAnalizar.addActionListener(e -> {

            // revisa que el usuario haya escrito algo
            String texto = txtCantidad.getText().trim();
            if (texto.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debes ingresar una cantidad de elementos.", "Campo vacío", JOptionPane.WARNING_MESSAGE);
                return; // no sigue si está vacío
            }

            // convierte el texto a número
            int tamano;
            try {
                tamano = Integer.parseInt(texto);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "La cantidad debe ser un número entero válido.", "Número inválido", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // valida que el número esté dentro del rango que acepta
            if (tamano < 10 || tamano > 200) {
                JOptionPane.showMessageDialog(this, "La cantidad debe estar entre 10 y 200.", "Fuera de rango", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // arma la lista de algoritmos según qué checkboxes estén marcados
            List<TipoAlgoritmo> seleccionados = new ArrayList<>();
            if (chkBubble.isSelected()) seleccionados.add(TipoAlgoritmo.BUBBLE_SORT);
            if (chkSelection.isSelected()) seleccionados.add(TipoAlgoritmo.SELECTION_SORT);
            if (chkInsertion.isSelected()) seleccionados.add(TipoAlgoritmo.INSERTION_SORT);
            if (chkMerge.isSelected()) seleccionados.add(TipoAlgoritmo.MERGE_SORT);
            if (chkQuick.isSelected()) seleccionados.add(TipoAlgoritmo.QUICK_SORT);
            if (chkHeap.isSelected()) seleccionados.add(TipoAlgoritmo.HEAP_SORT);

            // si no marcó ningún algoritmo, no hay nada que analizar
            if (seleccionados.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Selecciona al menos un algoritmo.", "Sin selección", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            // determina el tipo de arreglo según el botón marcado
            GeneradorDeArreglos.TipoArreglo tipoArreglo = null;
            if(rbtnOrdenados.isSelected()){
                tipoArreglo = GeneradorDeArreglos.TipoArreglo.ORDENADO;
            }else if(rbtnCasiOrdenado.isSelected()){
                tipoArreglo = GeneradorDeArreglos.TipoArreglo.CASI_ORDENADO;
            }else if(rbtnDesordenado.isSelected()){
                tipoArreglo = GeneradorDeArreglos.TipoArreglo.ALEATORIO;
            }else if(rbtnInvertido.isSelected()){
                tipoArreglo = GeneradorDeArreglos.TipoArreglo.INVERSO;
            }
            // aquí ya todo está validado y entonces se llama al controlador
            List<ResultadoOrdenamiento> resultados = new ControladorLaboratorio().analizar(tamano, tipoArreglo, seleccionados);
            FrmResultado ventanaResultado = new FrmResultado(resultados);
            ventanaResultado.setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgrpOrden;
    private itson.org.laboratorio_algoritmos.gui.utils.BotonRedondeado btnAnalizar;
    private itson.org.laboratorio_algoritmos.gui.utils.BotonRedondeado btnAnimacion;
    private javax.swing.JCheckBox chkBubble;
    private javax.swing.JCheckBox chkHeap;
    private javax.swing.JCheckBox chkInsertion;
    private javax.swing.JCheckBox chkMerge;
    private javax.swing.JCheckBox chkQuick;
    private javax.swing.JCheckBox chkSelection;
    private javax.swing.JLabel lblAlgoritmos;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCreacion;
    private javax.swing.JLabel lblOrden;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo1;
    private itson.org.laboratorio_algoritmos.gui.utils.PanelRedondeado panelRedondeado2;
    private itson.org.laboratorio_algoritmos.gui.utils.PanelRedondeado pnlCreacion;
    private itson.org.laboratorio_algoritmos.gui.utils.PanelRedondeado pnlHeader;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JRadioButton rbtnCasiOrdenado;
    private javax.swing.JRadioButton rbtnDesordenado;
    private javax.swing.JRadioButton rbtnInvertido;
    private javax.swing.JRadioButton rbtnOrdenados;
    private itson.org.laboratorio_algoritmos.gui.utils.TextFieldRedondeado txtCantidad;
    // End of variables declaration//GEN-END:variables
}
